title: ePages developer blog
url: https://devblog.epages.com
twitter_username: epagesdevs
github_username: ePages-de
youtube_username: UCI5hX9kgUGFnYpfxZYxlP0Q

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-admin
  - bourbon
  - neat

jekyll_admin:
  hidden_links:
    - pages
    - staticfiles
    - datafiles
    - configuration

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
