title: ePages developer blog
url: https://developer.epages.com
twitter_username: epagesdevs
github_username: ePages-de
youtube_username: UCI5hX9kgUGFnYpfxZYxlP0Q

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

include:
  - _pages

plugins:
  - jekyll-feed
  - jekyll-admin
  - bourbon
  - neat
  - rouge
  - jekyll-twitter-plugin

jekyll_admin:
  hidden_links:
    - pages
    - staticfiles
    - datafiles
    - configuration

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock

feed:
  path: /blog/feed.xml
